export { debounce } from './debounce'
export { unique, unique2 } from './quchong'
export { throttle, throttle2 } from './throttle'
export { reduce } from './reduce'
export { sortArray } from './quickSort'